name: Run Django test # workflow name

on:
  workflow_run:
    workflows: [ Rebase on main branch ] # depends on another workflow to be completed
    types: [ completed ]


jobs: # multiple jobs run in parallel by default

  build: # job id. Its not job name.
    name: run test  # optional
    runs-on: ubuntu-latest # os to run this job on
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # if rebase successful
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
      - name: Set up Python 3.8 # Task name in the job
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies # Task name in the job
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run django Tests # Task name in the job
        run: |
          python manage.py test
# TODO sometimes the branch is not rebasable when both master and feature branches are same. WHY?