name: Run Django test

on:
  push: # push event
    branches: [ main ] # when you push something directly to main branch
  pull_request:
    branches: [ main ] # when pr is created or updated to main branch

jobs: # multiple jobs run in parallel by default
  build: # job id. Its not job name.
    name: test job 1  # optional

    runs-on: ubuntu-latest # os to run this job on

    steps:
      - name: checkout branch
        uses: actions/checkout@v2
      - name: Set up Python 3.8 # Task name in the job
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies # Task name in the job
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run django Tests # Task name in the job
        run: |
          python manage.py test
