name: Rebase on main branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Django_test:
    name: Django test
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.8 # Task name in the job
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Dependencies # Task name in the job
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run django Tests
        run: |
          python manage.py test