name: Rebase on main branch

on:
  pull_request:
    branches: [ main ]

jobs:
  rebase:
    name: Rebase on main branch
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: automatic rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: echo
        run: |
          echo "Rebase on main branch"

      - name: Set up Python 3.8 # Task name in the job
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies # Task name in the job
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run django Tests # Task name in the job
        run: |
          python manage.py test

# TODO why is rebase running twice?